services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    ports:
      - "5080:5080"
    env_file:
      - .env
    environment:
      - ZO_ROOT_USER_EMAIL=${ZO_ROOT_USER_EMAIL:-admin@example.com}
      - ZO_ROOT_USER_PASSWORD=${ZO_ROOT_USER_PASSWORD:-Complexpass#123}
      - ZO_DATA_DIR=/data
    volumes:
      - openobserve-data:/data
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/otel-collector-config.yaml
    env_file:
      - .env
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - GH_PAT=${GH_PAT}
      - GITHUB_ORG=${GITHUB_ORG}
      - OPENOBSERVE_ENDPOINT=${OPENOBSERVE_ENDPOINT:-http://openobserve:5080/api/default/}
      - OPENOBSERVE_TOKEN=${OPENOBSERVE_TOKEN}
    depends_on:
      - openobserve
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge

volumes:
  openobserve-data: