extensions:
  bearertokenauth/github:
    token: ${GITHUB_PAT}

receivers:
  github/private-repo:
    initial_delay: 1s
    collection_interval: 60s
    scrapers:
      scraper:
        #metrics:  #Optional - uncomment to enable specific metrics
        #  vcs.contributor.count:
        #    enabled: true
        github_org: ${GITHUB_ORG}
        search_query: "org:${GITHUB_ORG} is:private"
        auth:
          authenticator: bearertokenauth/github

  github/pr-open:
    initial_delay: 1s
    collection_interval: 60s
    scrapers:
      scraper:
        #metrics:  #Optional - uncomment to enable specific metrics
        #  vcs.contributor.count:
        #    enabled: true
        github_org: ${GITHUB_ORG}
        search_query: "org:${GITHUB_ORG} is:pr is:open"
        auth:
          authenticator: bearertokenauth/github

exporters:
  otlphttp/openobserve:
    endpoint: ${OPENOBSERVE_ENDPOINT}
    headers:
      Authorization: Basic ${OPENOBSERVE_TOKEN}

service:
  extensions: [bearertokenauth/github]
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [github/private-repo, github/pr-open]
      exporters: [otlphttp/openobserve]