extensions:
  bearertokenauth/github:
    token: ${GITHUB_PAT}

receivers:
  github:
    initial_delay: 1s
    collection_interval: 60s
    scrapers:
        scraper:
            github_org: ${GITHUB_ORG}
            search_query: "org:${GITHUB_ORG}
            auth:
                authenticator: bearertokenauth/github

exporters:
  otlphttp/openobserve:
    endpoint: ${OPENOBSERVE_ENDPOINT}
    headers:
      Authorization: Basic ${OPENOBSERVE_TOKEN}

service:
  extensions: [bearertokenauth/github]
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [github]
      exporters: [otlphttp/openobserve]