extensions:
  bearertokenauth/github:
    token: ${env:GH_PAT}

receivers:
  github:
    initial_delay: 1s
    collection_interval: 300s
    scrapers:
        scraper:
            github_org: ${env:GITHUB_ORG}
            search_query: "${env:GITHUB_ORG_TYPE:-org}:${env:GITHUB_ORG}"
            # auth:
            #     authenticator: bearertokenauth/github

exporters:
  otlphttp/openobserve:
    endpoint: ${env:OPENOBSERVE_ENDPOINT}
    headers:
      Authorization: Basic ${env:OPENOBSERVE_TOKEN}

service:
  extensions: [bearertokenauth/github]
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [github]
      exporters: [otlphttp/openobserve]